### PR TITLE
New API for PIT and non PIT losses 

### PR DESCRIPTION
**Pull request by mpariente**
I'll take more time to describe what it does soon but this is ready for merging. 
Anyone wanting to review it is welcome !

Cheers !

### CODE REVIEW

**Comment by popcornell** [comment]
You added the `nosrc` functions for better efficiency in Speech Enhancement (1 speaker) applications ? 
I think we can merge and then i can pull request changes regarding sd-sdr later.

**Comment by mpariente** [comment]
> You added the `nosrc` functions for better efficiency in Speech Enhancement (1 speaker) applications ?

No actually, there are three ways to compute permutation invariant losses and the `nosrc` functions can be used for multisource separation as well. It's  a bit explained in the docstrings of the `PITLossWrapper` but I have to make a notebook to explain this clearly. 

`nosrc` functions expects signals without source dimensions, for example with shape `(batch, time)`.

**Comment by popcornell** [comment]
:+1: gotcha now. 
So `wo_src` and `w_src` are added for easier integration with loss functions code which is not pairwise right ? 

BTW The tests are a beautiful addition !

**Comment by mpariente** [comment]
Still didn't take time to make the notebook about the `PITLossWrapper` but I will eventually in the next few weeks.

**Pull request merged**
